backend/models/User.php
<?php
namespace backend\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends ActiveRecord implements IdentityInterface
{


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            [['username', 'password'], 'string', 'max' => 100]            
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'username' => 'Username',
            'password' => 'Password',
        ];
    } 
    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }
    public static function findIdentityByAccessToken($token, $type = null)
    {
          throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
    
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

  
    public function getId()
    {
        
        return $this->getPrimaryKey();
    }

    public function getAuthKey()
    {
        return $this->id;
    }
   
    public function validateAuthKey($authKey)
    {
        //throw new \yii\base\NotSupportedException();
    }
    public function validatePassword($password)
    {
        return $this->password === sha1($password);
    }
}

backend/models/Users.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property int $userId
 * @property string $username
 * @property string $userNama
 * @property string $password
 * @property string $userEmail
 * @property string $userTelephone
 * @property string $userAlamat
 * @property int $userPekerjaan
 * @property string $userFoto
 * @property string $userTanggalLahir
 * @property string $userJenisKelamin
 *
 * @property Jadwaldokter[] $jadwaldokters
 * @property Nota[] $notas
 * @property Pendaftaran[] $pendaftarans
 * @property Pendaftaran[] $pendaftarans0
 * @property Resep[] $reseps
 * @property Pekerjaan $userPekerjaan0
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userPekerjaan'], 'integer'],
            [['username', 'userNama', 'userEmail', 'userTelephone', 'userAlamat'], 'string', 'max' => 30],
            [['password'], 'string', 'max' => 100],
            [['userFoto'], 'string', 'max' => 50],
            [['userTanggalLahir'], 'string', 'max' => 20],
            [['userJenisKelamin'], 'string', 'max' => 15],
            [['userPekerjaan'], 'exist', 'skipOnError' => true, 'targetClass' => Pekerjaan::className(), 'targetAttribute' => ['userPekerjaan' => 'pekerjaanID']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'userId' => 'User ID',
            'username' => 'Username',
            'userNama' => 'User Nama',
            'password' => 'Password',
            'userEmail' => 'User Email',
            'userTelephone' => 'User Telephone',
            'userAlamat' => 'User Alamat',
            'userPekerjaan' => 'User Pekerjaan',
            'userFoto' => 'User Foto',
            'userTanggalLahir' => 'User Tanggal Lahir',
            'userJenisKelamin' => 'User Jenis Kelamin',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJadwaldokters()
    {
        return $this->hasMany(Jadwaldokter::className(), ['dokterID' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getNotas()
    {
        return $this->hasMany(Nota::className(), ['kasirID' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendaftarans()
    {
        return $this->hasMany(Pendaftaran::className(), ['pasienID' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendaftarans0()
    {
        return $this->hasMany(Pendaftaran::className(), ['dokterID' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReseps()
    {
        return $this->hasMany(Resep::className(), ['apotekerID' => 'userId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserPekerjaan0()
    {
        return $this->hasOne(Pekerjaan::className(), ['pekerjaanID' => 'userPekerjaan']);
    }
}

frontend/models/User.php
<?php
namespace frontend\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class User extends ActiveRecord implements IdentityInterface
{


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userPekerjaan'], 'integer'],
            [['username', 'password'], 'required'],
            [['username', 'password'], 'string', 'max' => 100]            
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'id',
            'username' => 'Username',
            'password' => 'Password',
            'userPekerjaan' => 'User Pekerjaan',
        ];
    } 
    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }
    public static function findIdentityByAccessToken($token, $type = null)
    {
          throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
    
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

  
    public function getId()
    {
        
        return $this->getPrimaryKey();
    }

    public function getAuthKey()
    {
        return $this->id;
    }

    public function getuserPekerjaan()
    {
        
        return $this->userPekerjaan;
    }
   
    public function validateAuthKey($authKey)
    {
        //throw new \yii\base\NotSupportedException();
    }
    public function validatePassword($password)
    {
        return $this->password === sha1($password);
    }

    public function getUserPekerjaan0()
    {
        return $this->hasOne(Pekerjaan::className(), ['pekerjaanID' => 'userPekerjaan']);
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Users;
use backend\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile; 
/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $pass = $model->password;
            $model->password= sha1($pass);
            $model->save();
            //upload file
            $model->userFoto = "585e4bf3cb11b227491c339a.png";
            $model->save();
            return $this->redirect(['view', 'id' => $model->userId]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //upload file
            $model->userFoto = UploadedFile::getInstance($model, 'userFoto');
            $model->userFoto->saveAs('gambar/' .$model->userFoto->baseName. '.' .$model->userFoto->extension);
            //save to database
            $model->userFoto = $model->userFoto->baseName. '.' .$model->userFoto->extension;
            $model->save();
            return $this->redirect(['view', 'id' => $model->userId]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/UsersController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Users;
use frontend\models\GantiPassword;
use frontend\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile; 
use yii\db\Query;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndexdokter()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('indexdokter', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndexkasir()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('indexkasir', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDokter()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('dokter', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionPasien()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('pasien', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /* 
        gawe shaf nek kate nyambungno file anyar garek kopas sing bagian index 
        actionIndex diganti action nama file e
        yang di render diganti index jadi nama file e
    */
    public function actionApoteker()
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('apoteker', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->password= sha1($model->password);
            $model->userPekerjaan = 1;
            $model->save();

            return $this->redirect(['site/login']);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model2 = new GantiPassword();

        if ($model2->load(Yii::$app->request->post())) {
            echo "halo";
            $model2->username= sha1($model2->username);
            $cekPassword = (new Query())
                ->select('count(*)')
                ->from('users')
                ->where(['password'=>$model2->username]);
            foreach($cekPassword->each() as $cek){
                if($cek['count(*)']){
                    if($model2->userNama == $model2->userEmail){
                        $model->password = sha1($model2->userNama);
                        $model->save();
                    }
                }
            }
            
            return $this->redirect(['view', 'id' => $model->userId]);
        }
        
        if ($model->load(Yii::$app->request->post())) {
            if(isset($model->userFoto)){
                $model->userFoto = UploadedFile::getInstance($model, 'userFoto');
                $model->userFoto->saveAs('gambar/' .$model->userFoto->baseName. '.' .$model->userFoto->extension);
                //save to database
                $model->userFoto = $model->userFoto->baseName. '.' .$model->userFoto->extension;
            
            }
            $model->save();
            return $this->redirect(['view', 'id' => $model->userId]);
        }


        return $this->render('update', [
            'model' => $model,
            'model2' => $model2,
        ]);
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/users/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'userNama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'userEmail')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'userJenisKelamin')->dropDownList(
            ['Laki-laki' => 'Laki-laki', 'Perempuan' => 'Perempuan']
    ); ?>
    <br>
    <div class="form-group text-center">
        <?= Html::submitButton('DAFTAR', ['class' => 'btn bg-primary', 'name' => 'login-button', 'style'=>'color:white']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/users/apoteker.php
<?php
use\yii\helpers\html;
use yii\grid\GridView;
use yii\db\Query;
use yii\helpers\Url;
/* @var $this yii\web\View */
/* @var $searchModel frontend\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Jadwal Dokter';
?>
<div class="users-index">
    <br>
    <h1>List Dokter</h1>
    <hr>
    <br>
    <div class="row">
        <div class="col-md-3">
            <h4>Kategori</h4>
            <hr>
            <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <?= Html::a('Semua', ['users/dokter'], ['class' => 'btn btn-success', 'style' => 'color:#006d55']) ?>
                <span class="badge badge-primary badge-pill">14</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <?= Html::a('Dokter Mata', ['users/dokter','category'=>'5'], ['class' => 'btn btn-success', 'style' => 'color:#006d55']) ?>
                <span class="badge badge-primary badge-pill">2</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            <?= Html::a('Dokter Jantung', ['users/dokter','category'=>'6'], ['class' => 'btn btn-success', 'style' => 'color:#006d55']) ?>
                <span class="badge badge-primary badge-pill">1</span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            <?= Html::a('Dokter Kulit', ['users/dokter','category'=>'7'], ['class' => 'btn btn-success', 'style' => 'color:#006d55']) ?>
                <span class="badge badge-primary badge-pill">1</span>
            </li>
            </ul>
        </div>
        <div class="col-md-9">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                <th scope="col">Nama</th>
                <th scope="col">Spesialis</th>
                <th scope="col">Lihat Jadwal</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <?php
            if(isset($_GET['category'])){
                $id = $_GET['category'];
                $dataUser = (new Query())
                    ->select('*')
                    ->from('users')
                    ->where('userPekerjaan = :id',  ['id'=>$id]);
            }
            else {
                $dataUser = (new Query())
                    ->select('*')
                    ->from('users')
                    ->where('userPekerjaan >=5 ');
            }
            foreach($dataUser->each() as $user){ 
                $jenisPekerjaan = (new Query())
                    ->select('*')
                    ->from('pekerjaan')
                    ->where(['pekerjaanID'=>$user['userPekerjaan']]);
                foreach($jenisPekerjaan->each() as $pekerjaan)
                ?>
                
                <td><?php echo $user['userNama'];?></td>
                <td><?php echo $pekerjaan['pekerjaanNama'];?></td>
                <td><?= Html::a('Lihat Jadwal', ['jadwaldokter/index','idDokter'=>$user['userId']], ['class' => 'btn btn-success']) ?></td>
                </tr>
                <?php 
            } ?> 
            </tbody>
            </table>
        </div>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <br>
    <br>
    <br>
    


</div>

frontend/views/users/indexdokter.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html; 
use yii\helpers\Url;
use yii\db\Query;
$this->title = 'Si Klinik';

$userQuery = (new Query())
  ->from('users')
  ->where(['userId'=>Yii::$app->user->id]);
foreach($userQuery->each() as $user){
  $nama = $user['userNama'];
}
?>
<br>
<div class="row">
    <div class="col-md-8"></div>
        <div class="col-md-4 text-right">
            <div class="alert alert-primary" role="alert">
                Selamat datang dr. <b><?php echo $nama;?></b>
        </div>
    </div>
</div>

<br>
<div class="row">
    <div class="col-md-4">
    <div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">List Pasien</h5>
        <div class="row">
            <div class="col-md-4">
                <img src="../../assets/icon/test.png" alt="" width="80" height="80">
            </div>
            <div class="col-md-8">
            <p class="card-text">Halaman yang menampilkan list pasien yang melakukan pemeriksaan.</p>
            </div>
        </div>
        <br>
        <?= Html::a('Kunjungi Laman', ['users/pasien'], ['class' => 'card-link'])?>
    </div>
    </div>
    </div>

    <div class="col-md-4">
    <div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">List Periksa</h5>
        <div class="row">
            <div class="col-md-4">
                <img src="../../assets/icon/periksa.png" alt="" width="80" height="80">
            </div>
            <div class="col-md-8">
            <p class="card-text">Halaman yang menampilkan list riwayat pemeriksaan pasien.</p> 
            </div>
        </div>
        <br>
        <?= Html::a('Kunjungi Laman', ['pendaftaran/listharian'], ['class' => 'card-link'])?>
    </div>
    </div>
    </div>

    <div class="col-md-4">
    <div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">List Jadwal</h5>
        <div class="row">
            <div class="col-md-4">
            <img src="../../assets/icon/questionnaire.png" alt="" width="80" height="80">
            </div>
            <div class="col-md-8">
            <p class="card-text">Halaman yang menampilkan list jadwal dokter.</p>
            </div>
        </div>
        <br>
        <?= Html::a('Kunjungi Laman', ['jadwaldokter/listjadwal','idDokter'=>Yii::$app->user->id], ['class' => 'card-link'])?>
    </div>
    </div>
    </div>

</div>
<br>
<br>

<div class="row">
<div class="col-md-8">
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<?php 
$jadwalQuery = (new Query())
->from('jadwaldokter');

foreach($jadwalQuery->each() as $jadwal){
    $pendaftaranQuery = (new Query())
    ->select('count(*)')
    ->from('pendaftaran')
    ->where(['jadwalID'=>$jadwal['jadwalID'],
    'pendaftaranStatus'=>'Sudah Periksa']);


    foreach($pendaftaranQuery->each() as $pendaftaran){
    $jumlah = $pendaftaran['count(*)'];
    }

}




?>
<script>

Highcharts.chart('container', {
    chart: {
        type: 'area'
    },
    title: {
        text: 'Grafik Pasien Pendaftar dan Pasien Hadir'
    },
    subtitle: {
        text: 'Sources: Si Klinik'
    },
    xAxis: {
        allowDecimals: false,
        labels: {
            formatter: function () {
                return this.value; // clean, unformatted number for year
            }
        }
    },
    yAxis: {
        title: {
            text: 'Jumlah Pasien'
        },
        labels: {
            formatter: function () {
                return this.value;
            }
        }
    },
    tooltip: {
        pointFormat: '{series.name} tercatat sebanyak <b>{point.y:,.0f}</b><br/> pada ID Jadwal Dokter : {point.x}'
    },
    plotOptions: {
        area: {
            pointStart: 60,
            marker: {
                enabled: false,
                symbol: 'circle',
                radius: 2,
                states: {
                    hover: {
                        enabled: true
                    }
                }
            }
        }
    },
    series: [{
        name: 'Pasien Hadir',
        data: [
            6, 6, 6, 6, 6, 6, 11, 32, 110, 235,
            369, 640, 1005, 1436, 2063, 3057, 4618, 6444, 9822, 15468,
            20434, 24126, 27387, 29459, 31056, 31982, 32040, 31233, 29224, 27342,
            26662, 26956, 27912, 28999, 28965, 27826, 25579, 25722, 24826, 24605,
            24304, 23464, 23708, 24099, 24357, 24237, 24401, 24344, 23586, 22380,
            21004, 17287, 14747, 13076, 12555, 12144, 11009, 10950, 10871, 10824,
            10577, 10527, 10475, 10421, 10358, 10295, 10104, 9914, 9620, 9326,
            5113, 5113, 4954, 4804, 4761, 4717, 4368, 4018
        ]
    }, {
        name: 'Pasien Pendaftar',
        data: [null, null, null, null, null, null, null, null, null, null,
            5, 25, 50, 120, 150, 200, 426, 660, 869, 1060,
            1605, 2471, 3322, 4238, 5221, 6129, 7089, 8339, 9399, 10538,
            11643, 13092, 14478, 15915, 17385, 19055, 21205, 23044, 25393, 27935,
            30062, 32049, 33952, 35804, 37431, 39197, 45000, 43000, 41000, 39000,
            37000, 35000, 33000, 31000, 29000, 27000, 25000, 24000, 23000, 22000,
            21000, 20000, 19000, 18000, 18000, 17000, 16000, 15537, 14162, 12787,
            12600, 11400, 5500, 4512, 4502, 4502, 4500, 4500
        ]
    }]
});
</script>
</div>

<div class="col-md-4">

</div>
</div>

<br>
<br>

frontend/views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\db\Query;

/* @var $this yii\web\View */
/* @var $model frontend\models\Users */

$this->title = "Profil";

\yii\web\YiiAsset::register($this);

$id = Yii::$app->user->id;
?>
<br>
<br>
<div class="col-md-12">
    <div class="text-right">
        <?= Html::a('EDIT', ['users/update','id'=>Yii::$app->user->id,'kategori'=>1], ['class' => 'btn btn-raised btn-primary', 'style' => 'color:white']) ?>
        <?= Html::a('PASSWORD', ['users/update','id'=>Yii::$app->user->id,'kategori'=>2], ['class' => 'btn btn-raised btn-info', 'style' => 'color:white']) ?>
    </div>
    <div class="row">
        <div class="col-md-4 text-center">
            <img src="../../assets/FOTO USER/download.png" alt="..." class="img-thumbnail">
        </div> 
        <?php
        $dataUser = (new Query())
            ->from('users')
            ->where(['userId'=>Yii::$app->user->id]);
        foreach($dataUser->each() as $user) {
        ?>
            <div class="col-md-8">
                <h1><b><?php echo $user['userNama']; ?></b></h1>
                <p><i>@<?php echo $user['username']; ?></i></p>
                <h6 style="color:#666768;"><?php echo $user['userEmail']; ?></h6>
                <h6><?php echo $user['userJenisKelamin']; ?></h6>
                <h6><?php echo $user['userTelephone']; ?></h6>
                <h6><i><?php echo $user['userAlamat']; ?></i></h6>
                <h6><b><?php echo $user['userTanggalLahir']; ?></b></h6>
                <br>
                <br>
                <br>
            </div>
        <?php } ?>
    </div>
   
</div>
<br>
<br><br>